version: '2.0'

services:
  app:
    container_name: truevision_designer
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '4200:4200'
      - '49153:49153'
    environment:
      - NODE_ENV=production
    working_dir: /app
    volumes:
      - ./:/app
      - /app/node_modules
#Volumes
volumes:
  dbdata:
    driver: local